# 1. EXPLORATORY DATA ANALYSIS (EDA)
print("="*50)
print("EXPLORATORY DATA ANALYSIS")
print("="*50)
print(f"Dataset Shape: {dataset.shape}")
print("\nDataset Info:")
print(dataset.info())
print("\nDescriptive Statistics:")
print(dataset.describe())
print("\nFirst 5 rows:")
print(dataset.head())

# Visualisasi hubungan antara Hours dan Scores
plt.figure(figsize=(10, 6))
plt.scatter(dataset['Hours'], dataset['Scores'], alpha=0.7, color='blue')
plt.title('Relationship Between Study Hours and Scores')
plt.xlabel('Hours Studied')
plt.ylabel('Exam Scores')
plt.grid(True)
plt.show()
